title: Arunima Prasad's Person Website
description: Working towards a degree in Computer Science and Digital Art, with a minor in Mathematics at Northeastern University.
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
